language: java
jdk: oraclejdk8
addons:
  sonarqube: true
env:
  global:
    - secure: "dJdfuEsdNmKTKppLBNi2AwZ90istRexnakyxfz4PLwaWKo2+P/j/cTRxpeWN2EQRA2CTRi0CuRMwDFjTZZdKotdwpBMk1b15BaLWVSWn+9LQ2OQlc/frv9prMXb0nI5ry3DsdVo9EhJ9esOy/TjO5g4kBg+NfNnAlXsqfrJyEGiGBwDqyw0xZXLsaq5YE14/3sn/oN3MnG9YTvmu82N5ffEas+Vcdo4VlDddGDYwlUGDTVWlx8EbQq22qJ/zJ7OebLn89HN0NLDTqj0wQvPcUUB5ekH2gfDJerSrHBj/y9ZTS5H62LqtUhwSNUa41xTguKygMre/rVC1wYWp6YFGqzMIesk3hJBAVm/qOBKoBLxohTfyNlZqQ2pL+KoknB/vUtbt60KxdvFatTZNZU5TGvX4kT/ptv9/CioBb4bKeDr/KwoIR+DC9wB0UYLFUAmP12RWo/Kb063DHKnjCti4tyDd4YhJsyiJ/D9AuN6KNbmNmmuKK71KRGGcleLyFc9hZ/ON4Dka0TIUWYzt3TBsSZALjevw5QnSBjeeIxyEShh47WB/Ep54t/dGBsLZbXNCcEk9q5wVqZAa8+QQ224kJL+EXWycMpWQ67aDVsHE7OoOW6XWdMcCSAw/X9p1r4VDFp9GRlFtBiLt4C5tip3lVztcjsNf/CxU0JveFm1wCHw="
script:
  - sonar-scanner -Dsonar.login=$DAYBREAK_TOKEN